### ISSUE TITLE
published anywhere publically?

### ISSUE THREAD

**Issue by quesojean** [risksense/ipaddr#7]
Hola, is there any chance this repo is published somewhere? I can't seem to find it (sonatype, bintray, etc) at the moment.
gracias!

**Comment by khatkar** [comment]
@quesojean Hola! This has not yet been published. Hopefully, by end of Sept.

**Comment by khatkar** [comment]
@quesojean Released! Please refer to Readme for artifact location.
`libraryDependencies += "com.risksense" % "ipaddr_2.12" % "1.0.2"`
